In [14]:
from __future__ import print_function
import numpy as np

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Input, Embedding, LSTM, Dense,Dropout,GRU
from keras.models import Model

In [15]:
 from sklearn.ensemble import GradientBoostingClassifier

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer

In [18]:
import pandas as pd

In [19]:
from keras.utils.np_utils import to_categorical

In [20]:
import gensim

ModuleNotFoundError: No module named 'gensim'

In [9]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [10]:
device_used = pd.read_csv("device_used.csv")

FileNotFoundError: File b'device_used.csv' does not exist

In [13]:
browser_used = pd.read_csv("browser_used.csv")

FileNotFoundError: File b'browser_used.csv' does not exist

In [11]:
len(train['User_ID'])

38932

In [12]:
len(test['User_ID'])

29404

In [14]:
data = pd.concat([train, test])

In [15]:
train = data

In [16]:
y_train = pd.read_csv("train.csv")

In [17]:
y_train.drop('User_ID', inplace=True, axis=1)
y_train.drop('Browser_Used', inplace=True, axis=1)
y_train.drop('Device_Used', inplace=True, axis=1)

In [18]:
y_train.drop('Description',inplace = True,axis=1)

In [19]:
train.drop('User_ID', inplace=True, axis=1)
train.drop('Browser_Used', inplace=True, axis=1)
train.drop('Device_Used', inplace=True, axis=1)
train.drop('Is_Response', inplace=True, axis=1)
train.head()

Description
0  The room was kind of clean but had a VERY stro...
1  I stayed at the Crown Plaza April -- - April -...
2  I booked this hotel through Hotwire at the low...
3  Stayed here with husband and sons on the way t...
4  My girlfriends and I stayed here to celebrate ...

In [13]:
train

Description
0      The room was kind of clean but had a VERY stro...
1      I stayed at the Crown Plaza April -- - April -...
2      I booked this hotel through Hotwire at the low...
3      Stayed here with husband and sons on the way t...
4      My girlfriends and I stayed here to celebrate ...
5      We had - rooms. One was very nice and clearly ...
6      My husband and I have stayed in this hotel a f...
7      My wife & I stayed in this glorious city a whi...
8      My boyfriend and I stayed at the Fairmont on a...
9      Wonderful staff, great location, but it was de...
10     Steps off Times Square, nice rooms, stayed - n...
11     Me, the Wife and - kids stayed here on Valenti...
12     We stay at the Jolly Madison over the Xmas per...
13     I highly recommend the Hawthorne Terrace as an...
14     I found the hotel clean and nicely located. Go...
15     Stayed at the Elan from --th to --th October a...
16     Priceline sent us to this hotel after acceptin...
17     Old and cheap furnitures,our chair was simply ...
18     We stayed here for - nights and were really ha...
19     The service was fine, but the hotel itself fel...
20     Having stayed at many Hilton properties, I exp...
21     This is everything you could want from a hotel...
22     I very much wanted to stay at a boutique hotel...
23     I really liked this hotel. The staff were wond...
24     My wife and spent - days there this month as a...
25     We stayed at this hotel for two nights over th...
26     Took a girls trip to LA and had no idea where ...
27     Stayed with my girlfriend for a long weekend. ...
28     I have stayed here numerous times and never be...
29     The public areas are nice to look at. The staf...
...                                                  ...
29374  the palomar was a nice hotel. nothing special,...
29375  For the most part this was a very good hotel. ...
29376  We booked the hotel through priceline and were...
29377  Paying a top price for a room but having to pa...
29378  Stayed here in March ---- . In San Antonio for...
29379  It is in a really convenient location. Walking...
29380  The rooms were very clean. \nThe staff went ab...
29381  -:The phone in living area not working( not fi...
29382  Have travelled throughout the world for work a...
29383  We got a too-good-to-be-true rate from a motor...
29384  I just got back this morning from New York and...
29385  We booked a double hotal room, arrived late to...
29386  It was too high but maybe that's the going rat...
29387  This property always comes through with the de...
29388  My husband and I frequently this hotel and we ...
29389  This hotel is a great location for a day or - ...
29390  My husband and I spend Labor Day weekend in NY...
29391  I had no problem with the hotel or the room it...
29392  Hotel Icon is a well-designed hotel built in a...
29393  I booked the Hotel Tomo because I got a good (...
29394  This hotel may not be the most glamorous in SF...
29395  Stayed here for - nights & had a room overlook...
29396  We stayed for three nights (June ----). The lo...
29397  We spent - nights in a king castia. The beds a...
29398  We booked our flight-hotel package on Expedia ...
29399  I stayed at the hotel and towers for a confere...
29400  Trying to stay within the Marriott family and ...
29401  We stayed for - nights with our little dog,ver...
29402  Stayed at the Yotel over the weekend and was v...
29403  The Blakely is is comfortable is every way: th...

[68336 rows x 1 columns]

In [20]:
train = np.array(train['Description'])

In [21]:
from gensim.models import Word2Vec

ModuleNotFoundError: No module named 'gensim'

In [25]:
tokenizer = RegexpTokenizer(r'\w+')

for i in range(0,68336):
    train[i] = tokenizer.tokenize(train[i])

KeyError: 0

In [26]:
dat = train

In [27]:
model99 = Word2Vec(dat,size = 100,window = 5,min_count =1)

NameError: name 'Word2Vec' is not defined

In [28]:
del(model99)

NameError: name 'model99' is not defined

In [29]:
b = np.empty([100])
c = np.empty([68336,400,100])
for i in range(0,68336):
    a = model99.wv[dat[i]]
    if(len(a) > 400):
        a = a[0:400]
    for j in range(0,(400-len(a))):
        a = np.vstack([a,b])
    c[i] = a

NameError: name 'model99' is not defined

In [30]:
main_input = Input(shape = (400,100))
lstm_out = GRU(200)(main_input)
output = Dense(1,activation = 'sigmoid')(lstm_out)
model = Model(inputs=main_input,outputs=output)

In [52]:
del c

NameError: name 'c' is not defined

In [31]:
y_train = pd.get_dummies(y_train,columns=['Is_Response'])

In [32]:
model.compile('adam', 'binary_crossentropy', metrics=['accuracy'])

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 400, 100)          0         
_________________________________________________________________
gru_1 (GRU)                  (None, 200)               180600    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 180,801
Trainable params: 180,801
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(X_train, Y_train,
          batch_size=1,
          epochs= 1,validation_data=[x_valid,y_valid])

NameError: name 'X_train' is not defined

In [34]:
result = model10.predict(test_nlp,batch_size=32)


NameError: name 'model10' is not defined

In [35]:
result[4]

NameError: name 'result' is not defined

In [36]:
np.savetxt(X=result,fname="gruv6.csv")

NameError: name 'result' is not defined

In [28]:
y_train = y_train['Is_Response_happy']

In [29]:
y_train = np.array(y_train)

In [86]:
x_test[1]

array([[  3.69829416e-01,  -1.05500199e-01,   1.26328576e+00, ...,
         -4.19324517e-01,  -2.29634547e+00,   2.09952402e+00],
       [ -7.55029678e-01,   2.45416021e+00,   3.91185069e+00, ...,
          3.37356663e+00,   4.78263982e-02,  -8.80642682e-02],
       [ -4.25771505e-01,  -9.16443408e-01,  -1.74876463e+00, ...,
         -2.24190667e-01,   1.80724487e-01,  -6.17789067e-02],
       ..., 
       [  1.45720962e-03,   1.77484678e-03,   3.88576519e-03, ...,
         -8.82284419e-04,  -4.03918664e-03,  -4.69804128e-03],
       [  1.45720962e-03,   1.77484678e-03,   3.88576519e-03, ...,
         -8.82284419e-04,  -4.03918664e-03,  -4.69804128e-03],
       [  1.45720962e-03,   1.77484678e-03,   3.88576519e-03, ...,
         -8.82284419e-04,  -4.03918664e-03,  -4.69804128e-03]])

In [30]:
Y_train = y_train[0:37932]

In [31]:
y_valid = y_train[37932:]

In [26]:
x_train = c[0:38932]

In [27]:
x_test = c[38932:]

In [33]:
Y_train[1]

0

In [53]:
x_test[2]

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [34]:
X_train = x_train[0:37932]

In [35]:
x_valid = x_train[37932:]

In [118]:
result = model.predict(x_test,batch_size=32)

In [66]:
result[15]

array([ 0.98209161], dtype=float32)

In [43]:
in2 = Input(shape = (400,100))
out2 = GRU(200,weights = model.layers[1].get_weights())(in2)
model2 = Model(inputs=in2,outputs=out2)

In [44]:
activations = model2.predict(X_train)

In [45]:
activations_valid = model2.predict(x_valid)

In [46]:
activations_test = model2.predict(x_test)

In [47]:
LSTM_train = activations

In [48]:
LSTM_valid = activations_valid


In [49]:
LSTM_test = activations_test

In [50]:
LSTM_test.shape

(29404, 200)

In [51]:
len(LSTM_valid)

1000

In [177]:
LSTM_test = activations

In [195]:
LSTM_valid = pd.DataFrame(LSTM_valid)
LSTM_valid = pd.concat([LSTM_valid,dummy_cols_valid],axis=1)
LSTM_valid.shape

(2000, 159)

In [196]:
LSTM_valid

0         1         2         3         4         5         6  \
0      0.225239 -0.258957 -0.007184  0.230849  0.058973 -0.025845 -0.156891   
1     -0.217152 -0.003030 -0.094956  0.126834  0.112026  0.170688 -0.098119   
2     -0.387972  0.156096 -0.014840  0.147186  0.184228  0.211021 -0.150233   
3      0.060413 -0.152933 -0.044332 -0.004447  0.022126 -0.019935 -0.035782   
4     -0.247179  0.135912 -0.055761  0.174787  0.185286  0.320671 -0.076785   
5     -0.004209 -0.087943 -0.073637  0.033977 -0.050010  0.052745  0.029605   
6     -0.171338  0.036254 -0.114302  0.169357  0.137011  0.428533 -0.044801   
7      0.104731 -0.068462 -0.000393 -0.045043 -0.006769 -0.053816  0.012703   
8      0.024172 -0.144366 -0.104300 -0.002618 -0.008613  0.038491  0.013404   
9      0.275879  0.215688  0.018065 -0.310457 -0.005969 -0.156934 -0.061384   
10    -0.026438 -0.241088 -0.149076  0.085241  0.093194  0.089993 -0.029314   
11     0.160143  0.114402  0.003721 -0.018682 -0.013435 -0.091265  0.025727   
12     0.015590 -0.029645 -0.038471  0.044179  0.046809  0.062336 -0.045673   
13     0.149254 -0.012174  0.007324 -0.114262 -0.004749 -0.051621  0.031270   
14    -0.310284  0.195496 -0.067557 -0.053657 -0.043838  0.403862  0.209452   
15    -0.495750  0.030346 -0.091078  0.293512  0.201023  0.415362 -0.235018   
16    -0.398155 -0.033215 -0.113823  0.274529  0.207170  0.168522 -0.225843   
17     0.063057 -0.042635 -0.038314 -0.001235  0.027536 -0.010673 -0.037300   
18     0.149432 -0.111333 -0.011762  0.144816  0.136263 -0.022062 -0.106599   
19    -0.177114 -0.006743 -0.053763  0.108158  0.130515  0.142560 -0.127559   
20    -0.350178  0.142355 -0.063825  0.166477  0.170651  0.297064 -0.062628   
21     0.090733 -0.158648 -0.030412  0.036508 -0.000946 -0.022844 -0.021678   
22    -0.318944  0.058059 -0.076607  0.279845  0.210405  0.228652 -0.242098   
23    -0.268273  0.077738 -0.083401  0.267662  0.190819  0.384993 -0.147725   
24    -0.151430 -0.033484 -0.162859  0.195510  0.229008  0.145092 -0.174741   
25    -0.444522  0.015427 -0.116696  0.318042  0.234933  0.666768 -0.199151   
26     0.288400  0.062973  0.029415 -0.257265 -0.005550 -0.138381  0.025531   
27     0.231255 -0.015237  0.069283  0.041473  0.084749 -0.017915 -0.106062   
28    -0.324471 -0.004702 -0.122820  0.221773  0.181245  0.303328 -0.191508   
29     0.069025  0.229228  0.013724 -0.209767 -0.006452 -0.135277  0.179554   
...         ...       ...       ...       ...       ...       ...       ...   
38902       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38903       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38904       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38905       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38906       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38907       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38908       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38909       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38910       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38911       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38912       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38913       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38914       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38915       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38916       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38917       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38918       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38919       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
38920       NaN       NaN       NaN       NaN       NaN       Na

In [145]:
dat1 = pd.DataFrame(activations)

In [163]:
dat = pd.read_csv("device_used.csv")

In [164]:
dat1 = dat[0:37932]

In [160]:
test3 = pd.concat([dat1,dat],axis=1)

In [161]:
test3.shape

(1000, 153)

In [215]:
model10=Sequential()
model10.add(Dense(300,activation="relu",input_shape=(209,)))
model10.add(Dense(280,activation="relu"))
model10.add(Dense(1,activation="sigmoid"))
model10.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_33 (Dense)             (None, 300)               63000     
_________________________________________________________________
dense_34 (Dense)             (None, 280)               84280     
_________________________________________________________________
dense_35 (Dense)             (None, 1)                 281       
Total params: 147,561
Trainable params: 147,561
Non-trainable params: 0
_________________________________________________________________


In [216]:
model10.compile('adam', 'binary_crossentropy', metrics=['accuracy'])

In [231]:
model10.fit(train_nlp, Y_train,
          batch_size=32,
          epochs= 1,validation_data=[valid_nlp,y_valid])

Train on 37932 samples, validate on 1000 samples
Epoch 1/1
37932/37932 [==============================] - 7s - loss: 0.1100 - acc: 0.9585 - val_loss: 0.3993 - val_acc: 0.8960


In [331]:
LSTM_test = np.array(LSTM_test)

In [227]:
result = model10.predict(x=test_nlp,batch_size=32)

In [228]:
result[4]

array([ 0.99997544], dtype=float32)

In [533]:
dummy_train = dummy_cols[0:37932]

In [536]:
dummy_valid.shape

(1000, 9)

In [535]:
dummy_valid = dummy_cols[37932:]

In [53]:
dummy_cols = pd.read_csv("Kish_train.csv")

In [54]:
dummy_train = dummy_cols[0:37932]

In [55]:
dummy_valid = dummy_cols[37932:]

In [70]:
dummy_cols_test = pd.read_csv("Kish_test.csv")

In [73]:
test_nlp = pd.concat([LSTM_test,dummy_cols_test],axis=1)

In [76]:
del LSTM_valid

In [72]:
LSTM_test = pd.DataFrame(LSTM_test)

In [560]:
test = pd.concat([LSTM_test,dummy_cols],axis=1)

In [67]:
dummy_valid = dummy_valid.drop('index', 1)

In [84]:
result[0]

array([ 0.00374541], dtype=float32)

In [339]:
LSTM_test = np.array(LSTM_test)

In [385]:
train_y_final = pd.concat([Y_train,y_valid])

In [390]:
train_y_final = np.array(train_y_final)

In [548]:
test = pd.concat([LSTM_valid,dummy_valid],axis=1)

In [550]:
test.shape

(1000, 99)

In [551]:
LSTM_valid = test

In [563]:
LSTM_test.shape

(29404, 99)

In [286]:
xgb = GradientBoostingClassifier(learning_rate=0.1,n_estimators=2000,max_depth = 5,loss = 'deviance')

In [287]:
xgb.fit(train_nlp,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=5,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=2000, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [282]:
result = xgb.predict(valid_nlp)

In [285]:
confusion_matrix(y_valid,result)

array([[253,  59],
       [ 56, 632]])

In [619]:
type()

numpy.ndarray

In [615]:
LSTM_test = np.array(LSTM_test)

In [66]:
dummy_valid

index  Browser_UsedEdge  Browser_UsedGoogle Chrome  \
0    37932                 0                          0   
1    37933                 0                          0   
2    37934                 0                          1   
3    37935                 0                          0   
4    37936                 0                          0   
5    37937                 0                          0   
6    37938                 0                          0   
7    37939                 0                          0   
8    37940                 0                          1   
9    37941                 1                          0   
10   37942                 0                          0   
11   37943                 0                          0   
12   37944                 0                          0   
13   37945                 0                          0   
14   37946                 0                          0   
15   37947                 0                          0   
16   37948                 0                          1   
17   37949                 0                          0   
18   37950                 0                          1   
19   37951                 0                          0   
20   37952                 0                          1   
21   37953                 0                          0   
22   37954                 1                          0   
23   37955                 0                          1   
24   37956                 0                          1   
25   37957                 1                          0   
26   37958                 0                          0   
27   37959                 0                          1   
28   37960                 1                          0   
29   37961                 0                          0   
..     ...               ...                        ...   
970  38902                 0                          0   
971  38903                 0                          0   
972  38904                 0                          1   
973  38905                 0                          0   
974  38906                 0                          0   
975  38907                 0                          0   
976  38908                 0                          0   
977  38909                 0                          0   
978  38910                 0                          1   
979  38911                 0                          0   
980  38912                 0                          0   
981  38913                 0                          0   
982  38914                 0                          0   
983  38915                 0                          0   
984  38916                 0                          1   
985  38917                 0                          1   
986  38918                 1                          0   
987  38919                 0                          0   
988  38920                 0                          0   
989  38921                 1                          0   
990  38922                 1                          0   
991  38923                 1                          0   
992  38924                 0                          0   
993  38925                 0                          0   
994  38926                 0                          0   
995  38927                 1                          0   
996  38928                 0                          0   
997  38929                 0                          0   
998  38930                 0                          1   
999  38931                 0                          0   

     Browser_UsedInternetExplorer  Browser_UsedMozilla Firefox  \
0                               0                            1   
1                               0                            1   
2                               0                            0   
3                               0                            1   
4               

In [122]:
LSTM_valid = pd.DataFrame(LSTM_valid)

In [79]:
test_nlp = np.array(test_nlp)